# Generated by Django 4.1.3 on 2022-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
